# Generated by Django 4.2.5 on 2023-11-04 12:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_alter_assignmentsub_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentsub',
            name='is_marked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentsub',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='roomsStu', to=settings.AUTH_USER_MODEL),
        ),
    ]
